In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r'C:\Users\ayush\PROJECTS\Github-Recommender\Data\repositories.csv')
df

,name,description,stars,forks,language,topics,updated_at,license,url
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,199328,76290,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-07T14:45:44Z,Apache License 2.0,https://github.com/tensorflow/tensorflow
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164954,34483,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-07T14:45:18Z,Apache License 2.0,https://github.com/huggingface/transformers
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90242,22203,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-07T14:30:47Z,MIT License,https://github.com/microsoft/ML-For-Beginners
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82938,15277,Python,[],2026-09-07T14:29:49Z,NaN,https://github.com/fighting41love/funNLP
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74274,15638,Python,[],2026-09-07T14:33:36Z,Other,https://github.com/josephmisiti/awesome-machin...
...,...,...,...,...,...,...,...,...,...
456,PacktPublishing/LLM-Engineers-Handbook,The LLM's practical guide: From the fundamenta...,5315,1289,Python,"['aws', 'fine-tuning-llm', 'genai', 'llm', 'll...",2026-09-06T00:40:19Z,MIT License,https://github.com/PacktPublishing/LLM-Enginee...
457,kelvins/awesome-mlops,:sunglasses: A curated list of awesome MLOps t...,5266,775,Python,"['ai', 'awesome', 'data-science', 'machine-lea...",2026-09-06T15:43:47Z,NaN,https://github.com/kelvins/awesome-mlops
458,argilla-io/argilla,Argilla is a collaboration tool for AI enginee...,5101,506,Python,"['active-learning', 'ai', 'annotation-tool', '...",2026-09-07T12:27:00Z,Apache License 2.0,https://github.com/argilla-io/argilla
459,tencentmusic/cube-studio,cube studio开源云原生一站式机器学习/深度学习/大模型AI平台，mlops算法链路...,5077,880,NaN,"['ai', 'aihub', 'argo', 'automl', 'deepseek', ...",2026-09-06T05:39:12Z,Other,https://github.com/tencentmusic/cube-studio
460,SeldonIO/seldon-core,"An MLOps framework to package, deploy, monitor...",4779,867,Go,"['aiops', 'deployment', 'kubernetes', 'machine...",2026-09-07T04:23:52Z,Other,https://github.com/SeldonIO/seldon-core

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 461 entries, 0 to 460
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         461 non-null    str
 1   description  457 non-null    str
 2   stars        461 non-null    int64
 3   forks        461 non-null    int64
 4   language     396 non-null    str
 5   topics       461 non-null    str
 6   updated_at   461 non-null    str
 7   license      390 non-null    str
 8   url          461 non-null    str
dtypes: int64(2), str(7)
memory usage: 32.5 KB

In [5]:
df.describe()

               stars         forks
count     461.000000    461.000000
mean    15056.633406   3286.310195
std     25408.382229   7326.094726
min      1179.000000     26.000000
25%      4360.000000    630.000000
50%      8032.000000   1349.000000
75%     17469.000000   3408.000000
max    368503.000000  76290.000000

In [6]:
df.isnull().sum()

name            0
description     4
stars           0
forks           0
language       65
topics          0
updated_at      0
license        71
url             0
dtype: int64

In [7]:
df["language"].value_counts()

language
Python              172
Jupyter Notebook     72
JavaScript           33
TypeScript           27
C++                  24
Go                   14
HTML                  9
Java                  6
Rust                  6
TeX                   5
C                     4
C#                    4
Shell                 4
Ruby                  3
MDX                   3
PHP                   2
Scala                 1
CSS                   1
Dart                  1
R                     1
SCSS                  1
Astro                 1
Markdown              1
MATLAB                1
Name: count, dtype: int64

In [3]:
import pandas as pd
df=pd.read_csv(r'C:\Users\ayush\PROJECTS\Github-Recommender\Data\repositories.csv')
df

,name,description,stars,forks,language,topics,updated_at,license,url,readme
0,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,199328,76290,C++,"['deep-learning', 'deep-neural-networks', 'dis...",2026-09-07T14:45:44Z,Apache License 2.0,https://github.com/tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www...."
1,huggingface/transformers,🤗 Transformers: the model-definition framework...,164954,34483,Python,"['audio', 'deep-learning', 'deepseek', 'gemma'...",2026-09-07T14:45:18Z,Apache License 2.0,https://github.com/huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...
2,microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",90242,22203,Jupyter Notebook,"['data-science', 'education', 'machine-learnin...",2026-09-07T14:30:47Z,MIT License,https://github.com/microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...
3,fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,82938,15277,Python,[],2026-09-07T14:29:49Z,NaN,https://github.com/fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312..."
4,josephmisiti/awesome-machine-learning,A curated list of awesome Machine Learning fra...,74274,15638,Python,[],2026-09-07T14:33:36Z,Other,https://github.com/josephmisiti/awesome-machin...,# Awesome Machine Learning [![Awesome](https:/...
...,...,...,...,...,...,...,...,...,...,...
456,PacktPublishing/LLM-Engineers-Handbook,The LLM's practical guide: From the fundamenta...,5315,1289,Python,"['aws', 'fine-tuning-llm', 'genai', 'llm', 'll...",2026-09-06T00:40:19Z,MIT License,https://github.com/PacktPublishing/LLM-Enginee...,NaN
457,kelvins/awesome-mlops,:sunglasses: A curated list of awesome MLOps t...,5266,775,Python,"['ai', 'awesome', 'data-science', 'machine-lea...",2026-09-06T15:43:47Z,NaN,https://github.com/kelvins/awesome-mlops,NaN
458,argilla-io/argilla,Argilla is a collaboration tool for AI enginee...,5101,506,Python,"['active-learning', 'ai', 'annotation-tool', '...",2026-09-07T12:27:00Z,Apache License 2.0,https://github.com/argilla-io/argilla,NaN
459,tencentmusic/cube-studio,cube studio开源云原生一站式机器学习/深度学习/大模型AI平台，mlops算法链路...,5077,880,NaN,"['ai', 'aihub', 'argo', 'automl', 'deepseek', ...",2026-09-06T05:39:12Z,Other,https://github.com/tencentmusic/cube-studio,NaN
460,SeldonIO/seldon-core,"An MLOps framework to package, deploy, monitor...",4779,867,Go,"['aiops', 'deployment', 'kubernetes', 'machine...",2026-09-07T04:23:52Z,Other,https://github.com/SeldonIO/seldon-core,NaN

In [18]:
df['readme'].isnull().sum()

np.int64(402)

In [29]:
(df["readme"] == "").sum()

np.int64(0)

In [26]:
df["readme"].str.len().describe()

count        59.000000
mean      40482.813559
std       90098.356116
min        1842.000000
25%        5356.500000
50%        9007.000000
75%       28883.000000
max      505845.000000
Name: readme, dtype: float64

In [31]:
df[["name", "readme"]].head(5)

,name,readme
0,tensorflow/tensorflow,"<div align=""center"">\n <img src=""https://www...."
1,huggingface/transformers,<!---\nCopyright 2020 The HuggingFace Team. Al...
2,microsoft/ML-For-Beginners,[![GitHub license](https://img.shields.io/gith...
3,fighting41love/funNLP,"<center>\n <img style=""border-radius: 0.312..."
4,josephmisiti/awesome-machine-learning,# Awesome Machine Learning [![Awesome](https:/...

In [30]:
print("Empty READMEs:", (df["readme"] == "").sum())

Empty READMEs: 0